/* eslint-disable max-len */
// Define Action Types
export const FETCH_INCIDENTS_REQUESTED = 'FETCH_INCIDENTS_REQUESTED';
export const FETCH_INCIDENTS_COMPLETED = 'FETCH_INCIDENTS_COMPLETED';
export const FETCH_INCIDENTS_ERROR = 'FETCH_INCIDENTS_ERROR';

// export const REFRESH_INCIDENTS_REQUESTED = 'REFRESH_INCIDENTS_REQUESTED';
// export const REFRESH_INCIDENTS_COMPLETED = 'REFRESH_INCIDENTS_COMPLETED';
// export const REFRESH_INCIDENTS_ERROR = 'REFRESH_INCIDENTS_ERROR';

export const FETCH_INCIDENT_NOTES_REQUESTED = 'FETCH_INCIDENT_NOTES_REQUESTED';
export const FETCH_INCIDENT_NOTES_COMPLETED = 'FETCH_INCIDENT_NOTES_COMPLETED';
export const FETCH_INCIDENT_NOTES_ERROR = 'FETCH_INCIDENT_NOTES_ERROR';

// export const FETCH_ALL_INCIDENT_NOTES_REQUESTED = 'FETCH_ALL_INCIDENT_NOTES_REQUESTED';
// export const FETCH_ALL_INCIDENT_NOTES_COMPLETED = 'FETCH_ALL_INCIDENT_NOTES_COMPLETED';
// export const FETCH_ALL_INCIDENT_NOTES_ERROR = 'FETCH_ALL_INCIDENT_NOTES_ERROR';

export const FETCH_INCIDENT_ALERTS_REQUESTED = 'FETCH_INCIDENT_ALERTS_REQUESTED';
export const FETCH_INCIDENT_ALERTS_COMPLETED = 'FETCH_INCIDENT_ALERTS_COMPLETED';
export const FETCH_INCIDENT_ALERTS_ERROR = 'FETCH_INCIDENT_ALERTS_ERROR';

export const UPDATE_INCIDENTS_LIST = 'UPDATE_INCIDENTS_LIST';
export const UPDATE_INCIDENTS_LIST_COMPLETED = 'UPDATE_INCIDENTS_LIST_COMPLETED';
export const UPDATE_INCIDENTS_LIST_ERROR = 'UPDATE_INCIDENTS_LIST_ERROR';

export const PROCESS_LOG_ENTRIES = 'PROCESS_LOG_ENTRIES';
export const PROCESS_LOG_ENTRIES_COMPLETED = 'PROCESS_LOG_ENTRIES_COMPLETED';
export const PROCESS_LOG_ENTRIES_ERROR = 'PROCESS_LOG_ENTRIES_ERROR';

export const UPDATE_INCIDENT_ALERTS = 'UPDATE_INCIDENT_ALERTS';
export const UPDATE_INCIDENT_ALERTS_COMPLETED = 'UPDATE_INCIDENT_ALERTS_COMPLETED';
export const UPDATE_INCIDENT_ALERTS_ERROR = 'UPDATE_INCIDENT_ALERTS_ERROR';

export const UPDATE_INCIDENT_NOTES = 'UPDATE_INCIDENT_NOTES';
export const UPDATE_INCIDENT_NOTES_COMPLETED = 'UPDATE_INCIDENT_NOTES_COMPLETED';
export const UPDATE_INCIDENT_NOTES_ERROR = 'UPDATE_INCIDENT_NOTES_ERROR';

export const FILTER_INCIDENTS_LIST = 'FILTER_INCIDENTS_LIST';
export const FILTER_INCIDENTS_LIST_COMPLETED = 'FILTER_INCIDENTS_LIST_COMPLETED';
export const FILTER_INCIDENTS_LIST_ERROR = 'FILTER_INCIDENTS_LIST_ERROR';

export const FILTER_INCIDENTS_LIST_BY_PRIORITY = 'FILTER_INCIDENTS_LIST_BY_PRIORITY';
export const FILTER_INCIDENTS_LIST_BY_PRIORITY_COMPLETED = 'FILTER_INCIDENTS_LIST_BY_PRIORITY_COMPLETED';
export const FILTER_INCIDENTS_LIST_BY_PRIORITY_ERROR = 'FILTER_INCIDENTS_LIST_BY_PRIORITY_ERROR';

export const FILTER_INCIDENTS_LIST_BY_STATUS = 'FILTER_INCIDENTS_LIST_BY_STATUS';
export const FILTER_INCIDENTS_LIST_BY_STATUS_COMPLETED = 'FILTER_INCIDENTS_LIST_BY_STATUS_COMPLETED';
export const FILTER_INCIDENTS_LIST_BY_STATUS_ERROR = 'FILTER_INCIDENTS_LIST_BY_STATUS_ERROR';

export const FILTER_INCIDENTS_LIST_BY_URGENCY = 'FILTER_INCIDENTS_LIST_BY_URGENCY';
export const FILTER_INCIDENTS_LIST_BY_URGENCY_COMPLETED = 'FILTER_INCIDENTS_LIST_BY_URGENCY_COMPLETED';
export const FILTER_INCIDENTS_LIST_BY_URGENCY_ERROR = 'FILTER_INCIDENTS_LIST_BY_URGENCY_ERROR';

export const FILTER_INCIDENTS_LIST_BY_TEAM = 'FILTER_INCIDENTS_LIST_BY_TEAM';
export const FILTER_INCIDENTS_LIST_BY_TEAM_COMPLETED = 'FILTER_INCIDENTS_LIST_BY_TEAM_COMPLETED';
export const FILTER_INCIDENTS_LIST_BY_TEAM_ERROR = 'FILTER_INCIDENTS_LIST_BY_TEAM_ERROR';

export const FILTER_INCIDENTS_LIST_BY_ESCALATION_POLICY = 'FILTER_INCIDENTS_LIST_BY_ESCALATION_POLICY';
export const FILTER_INCIDENTS_LIST_BY_ESCALATION_POLICY_COMPLETED = 'FILTER_INCIDENTS_LIST_BY_ESCALATION_POLICY_COMPLETED';
export const FILTER_INCIDENTS_LIST_BY_ESCALATION_POLICY_ERROR = 'FILTER_INCIDENTS_LIST_BY_ESCALATION_POLICY_ERROR';

export const FILTER_INCIDENTS_LIST_BY_SERVICE = 'FILTER_INCIDENTS_LIST_BY_SERVICE';
export const FILTER_INCIDENTS_LIST_BY_SERVICE_COMPLETED = 'FILTER_INCIDENTS_LIST_BY_SERVICE_COMPLETED';
export const FILTER_INCIDENTS_LIST_BY_SERVICE_ERROR = 'FILTER_INCIDENTS_LIST_BY_SERVICE_ERROR';

export const FILTER_INCIDENTS_LIST_BY_USER = 'FILTER_INCIDENTS_LIST_BY_USER';
export const FILTER_INCIDENTS_LIST_BY_USER_COMPLETED = 'FILTER_INCIDENTS_LIST_BY_USER_COMPLETED';
export const FILTER_INCIDENTS_LIST_BY_USER_ERROR = 'FILTER_INCIDENTS_LIST_BY_USER_ERROR';

export const FILTER_INCIDENTS_LIST_BY_QUERY = 'FILTER_INCIDENTS_LIST_BY_QUERY';
export const FILTER_INCIDENTS_LIST_BY_QUERY_COMPLETED = 'FILTER_INCIDENTS_LIST_BY_QUERY_COMPLETED';
export const FILTER_INCIDENTS_LIST_BY_QUERY_ERROR = 'FILTER_INCIDENTS_LIST_BY_QUERY_ERROR';

// Define Actions
export const getIncidentsAsync = () => ({
  type: FETCH_INCIDENTS_REQUESTED,
});

// export const refreshIncidentsAsync = () => ({
//   type: REFRESH_INCIDENTS_REQUESTED,
// });

// export const getIncidentNotesAsync = (incidentId) => ({
//   type: FETCH_INCIDENT_NOTES_REQUESTED,
//   incidentId,
// });

// export const getAllIncidentNotesAsync = () => ({
//   type: FETCH_ALL_INCIDENT_NOTES_REQUESTED,
// });

export const getIncidentAlertsAsync = (incidentId) => ({
  type: FETCH_INCIDENT_ALERTS_REQUESTED,
  incidentId,
});

export const getIncidentNotesAsync = (incidentId) => ({
  type: FETCH_INCIDENT_NOTES_REQUESTED,
  incidentId,
});

export const updateIncidentsListAsync = (addList = [], updateList = [], removeList = []) => ({
  type: UPDATE_INCIDENTS_LIST,
  addList,
  updateList,
  removeList,
});

export const updateIncidentAlerts = (incidentId, alerts = []) => ({
  type: UPDATE_INCIDENT_ALERTS,
  incidentId,
  alerts,
});

export const updateIncidentNotes = (incidentId, notes = []) => ({
  type: UPDATE_INCIDENT_NOTES,
  incidentId,
  notes,
});

export const filterIncidents = () => ({
  type: FILTER_INCIDENTS_LIST,
});

export const filterIncidentsByPriority = (incidentPriority = []) => ({
  type: FILTER_INCIDENTS_LIST_BY_PRIORITY,
  incidentPriority,
});

export const filterIncidentsByStatus = (incidentStatus = []) => ({
  type: FILTER_INCIDENTS_LIST_BY_PRIORITY,
  incidentStatus,
});

export const filterIncidentsByUrgency = (incidentUrgency = []) => ({
  type: FILTER_INCIDENTS_LIST_BY_URGENCY,
  incidentUrgency,
});

export const filterIncidentsByTeam = (teamIds = []) => ({
  type: FILTER_INCIDENTS_LIST_BY_TEAM,
  teamIds,
});

export const filterIncidentsByEscalationPolicy = (escalationPolicyIds = []) => ({
  type: FILTER_INCIDENTS_LIST_BY_ESCALATION_POLICY,
  escalationPolicyIds,
});

export const filterIncidentsByService = (serviceIds = []) => ({
  type: FILTER_INCIDENTS_LIST_BY_SERVICE,
  serviceIds,
});

export const filterIncidentsByUser = (userIds = []) => ({
  type: FILTER_INCIDENTS_LIST_BY_USER,
  userIds,
});

export const filterIncidentsByQuery = (searchQuery = '') => ({
  type: FILTER_INCIDENTS_LIST_BY_QUERY,
  searchQuery,
});
