name: Custom Cypress Browsers image

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Only run when changes are made to the Dockerfile
  pull_request:
    branches: [ "develop" ]
    paths: [ "cypress/Dockerfile" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-cypress-browsers

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          labels: |
            org.opencontainers.image.title=pd-live-react-cypress-browsers
            org.opencontainers.image.description=Custom Cypress Browsers image for PD Live React testing
            org.opencontainers.image.source=https://github.com/PagerDuty/pd-live-react/tree/main/cypress
            org.opencontainers.image.url=https://github.com/PagerDuty/pd-live-react/tree/main/cypress

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: cypress
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
